export const state = {
  projectPath: null,
  projectName: null,
  docs: [],
  binder: { rootIds: [], nodes: {}, order: [] },
  currentDocId: null,
  currentDoc: null,
  docMetaCollapsed: false,
  selectedDocId: null,
  selectedBinderNodeId: null,
  collapsedFolderIds: new Set(),
  dirty: false,
  fontSize: 18,
  chapterFilterQuery: '',
  binderPinnedOnly: false,
  localFindQuery: '',
  localFindResults: [],
  globalSearchQuery: '',
  globalSearchResults: [],
  docStats: new Map(),
  totalCounts: { withSpaces: 0, withoutSpaces: 0 },
  currentCounts: { withSpaces: 0, withoutSpaces: 0 },
  selectionCounts: { withSpaces: 0, withoutSpaces: 0 },
  selectionActive: false,
  viewMode: 'editor',
  boardQuery: '',
  boardStatusFilter: 'all',
  boardMissingSynopsisOnly: false,
  projectMeta: null,
  openProjectNoteId: null,
  activeProjectNoteId: null,
  historyEntries: [],
  mobilePreviewOpen: false,
  focusMode: false,
  characters: [],
  characterFormId: null,
};
